# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

export SADIR=/home/ap/sa/sa
export LD_LIBRARY_PATH=$SADIR/lib64:$LD_LIBRARY_PATH
export LANG=zh_CN.UTF-8

export JAVA_HOME=/usr/local/java/jdk1.6.0_43
export PATH=$PATH:$JAVA_HOME/bin

alias jar="/usr/local/java/jdk1.6.0_43/bin/jar"

